comentario:
    path:     /{_locale}/lista
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:index" }
    requirements:
        _locale: en|es

comentario_show:
    path:     /{_locale}/{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:show" }
    requirements:
        _locale: en|es    

#comentario_new:
#    path:     /new
#    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:new" }

comentario_create:
    path:     /{_locale}/create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:create" }
    requirements: { _method: post , _locale: en|es }

#comentario_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:edit" }

comentario_update:
    path:     /{_locale}/{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:update" }
    requirements: { _method: post|put , _locale: en|es }

comentario_delete:
    path:     /{_locale}/{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Comentario:delete" }
    requirements: { _method: post|delete , _locale: en|es }