conozcanos:
    path:     /
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:show" }

conozcanos_show:
    path:     /show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:show" }

conozcanos_new:
    path:     /new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:new" }

conozcanos_create:
    path:     /create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:create" }
    requirements: { _method: post }

conozcanos_edit:
    path:     /{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:edit" }

conozcanos_update:
    path:     /{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:update" }
    requirements: { _method: post|put }

conozcanos_delete:
    path:     /{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Conozcanos:delete" }
    requirements: { _method: post|delete }
