contenido:
    path:     /{_locale}/
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:index" }
    requirements:
        _locale: en|es

contenido_show:
    path:     /{_locale}/{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:show" }
    requirements:
        _locale: en|es

contenido_new:
    path:     /{_locale}/new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:new" }
    requirements:
        _locale: en|es

contenido_create:
    path:     /{_locale}/create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:create" }
    requirements: { _method: post , _locale: en|es }

contenido_edit:
    path:     /{_locale}/{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:edit" }
    requirements:
        _locale: en|es

contenido_update:
    path:     /{_locale}/{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:update" }
    requirements: { _method: post|put , _locale: en|es }

contenido_delete:
    path:     /{_locale}/{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:delete" }
    requirements: { _method: post|delete|get , _locale: en|es }
    
contenido_home:
    path:     /{_locale}/home
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Contenido:home" }
    requirements:
        _locale: en|es
