definiciones:
    pattern:  /
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:index" }

definiciones_show:
    pattern:  /{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:show" }

definiciones_new:
    pattern:  /new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:new" }

definiciones_create:
    pattern:  /create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:create" }
    requirements: { _method: post }

definiciones_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:edit" }

definiciones_update:
    pattern:  /{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:update" }
    requirements: { _method: post|put }

definiciones_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Definiciones:delete" }
    requirements: { _method: post|delete }
