encabezado_edit:
    path:     /{_locale}/{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:edit" }
    requirements:
        _locale: en|es

encabezado_update:
    path:     /{_locale}/{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:update" }
    requirements: { _method: post|put , _locale: en|es }
