encabezado:
    path:     /
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:index" }

encabezado_show:
    path:     /{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:show" }

encabezado_new:
    path:     /new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:new" }

encabezado_create:
    path:     /create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:create" }
    requirements: { _method: post }

encabezado_edit:
    path:     /{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:edit" }

encabezado_update:
    path:     /{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:update" }
    requirements: { _method: post|put }

encabezado_delete:
    path:     /{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Encabezado:delete" }
    requirements: { _method: post|delete }
