generaciones:
    pattern:  /
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:show" }

generaciones_show:
    pattern:  /show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:show" }

generaciones_new:
    pattern:  /new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:new" }

generaciones_create:
    pattern:  /create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:create" }
    requirements: { _method: post }

generaciones_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:edit" }

generaciones_update:
    pattern:  /{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:update" }
    requirements: { _method: post|put }

generaciones_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Generaciones:delete" }
    requirements: { _method: post|delete }
