noticia:
    path:     /{_locale}/
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:index" }
    requirements:
        _locale: en|es

noticia_show:
    path:     /{_locale}/{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:show" }
    requirements:
        _locale: en|es

noticia_new:
    path:     /{_locale}/new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:new" }
    requirements:
        _locale: en|es

noticia_create:
    path:     /{_locale}/create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:create" }
    requirements: { _method: post , _locale: en|es }

noticia_edit:
    path:     /{_locale}/{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:edit" }
    requirements:
        _locale: en|es

noticia_update:
    path:     /{_locale}/{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:update" }
    requirements: { _method: post|put , _locale: en|es }

noticia_delete:
    path:     /{_locale}/{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:delete" }
    requirements: { _method: post|delete , _locale: en|es }
