noticia:
    path:     /
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:index" }

noticia_show:
    path:     /{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:show" }

noticia_new:
    path:     /new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:new" }

noticia_create:
    path:     /create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:create" }
    requirements: { _method: post }

noticia_edit:
    path:     /{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:edit" }

noticia_update:
    path:     /{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:update" }
    requirements: { _method: post|put }

noticia_delete:
    path:     /{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Noticia:delete" }
    requirements: { _method: post|delete }
