programacion:
    path:     /
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:index" }

programacion_show:
    path:     /{id}/show
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:show" }

programacion_new:
    path:     /new
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:new" }

programacion_create:
    path:     /create
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:create" }
    requirements: { _method: post }

programacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:edit" }

programacion_update:
    path:     /{id}/update
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:update" }
    requirements: { _method: post|put }

programacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:delete" }
    requirements: { _method: post|delete|get }
    
programacion_selectMonth:
    path:     /selectMonth
    defaults: { _controller: "RUGCProgramacionCatarsisBundle:Programacion:selectMonth" }
#    requirements: { _method: post|delete|get }    
