security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
#                login_path: /programacion
                use_forward: true
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            
            logout:       
                path: fos_user_security_logout
                target: /contenido/es/home
            anonymous:    true
            access_denied_url: /contenido/home
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICAT}
        
        
        - { path: ^/comentario/lista, role: ROLE_ADMIN }
        - { path: ^/comentario/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/comentario/.*/show, role: ROLE_ADMIN }
        - { path: ^/comentario/.*/update, role: ROLE_ADMIN }
        - { path: ^/comentario/.*/delete, role: ROLE_ADMIN }
        
        - { path: ^/contenido/new, role: ROLE_ADMIN }        
        - { path: ^/contenido/.*/edit, role: ROLE_ADMIN }
        - { path: ^/contenido/.*/delete, role: ROLE_ADMIN }
        - { path: ^/contenido/.*/confirm, role: ROLE_ADMIN }
        
        - { path: ^/encabezado/.*/edit, role: ROLE_ADMIN }
        - { path: ^/encabezado/.*/delete, role: ROLE_ADMIN }
        
        - { path: ^/programacion/new, role: ROLE_ADMIN }
        - { path: ^/programacion/.*/edit, role: ROLE_ADMIN }
        - { path: ^/programacion/.*/delete, role: ROLE_ADMIN }
        - { path: ^/programacion/selectMonth, role: ROLE_ADMIN }
        - { path: ^/programacion/.*/delete_imagen, role: ROLE_ADMIN }
        
        - { path: ^/enlace/new, role: ROLE_ADMIN }
        - { path: ^/enlace/.*/edit, role: ROLE_ADMIN }
        - { path: ^/enlace/.*/delete, role: ROLE_ADMIN }
