rugc_programacion_catarsis_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: RUGCProgramacionCatarsisBundle:Default:index }
   
definiciones:
    pattern:  /deficiones
    defaults: { _controller: FrameworkBundle:Template:template, template:  'RUGCProgramacionCatarsisBundle:Static:Definiciones.html.twig' }
         
RUGCProgramacionCatarsisBundle_encabezado:
        resource: "@RUGCProgramacionCatarsisBundle/Resources/config/routing/encabezado.yml"
        prefix:   /encabezado
        
RUGCProgramacionCatarsisBundle_programacion:
        resource: "@RUGCProgramacionCatarsisBundle/Resources/config/routing/programacion.yml"
        prefix:   /programacion 
        
RUGCProgramacionCatarsisBundle_contenido:
        resource: "@RUGCProgramacionCatarsisBundle/Resources/config/routing/contenido.yml"
        prefix:   /contenido
