parameters:
#    rugc_programacion_catarsis.example.class: RUGC\ProgramacionCatarsisBundle\Example

services:
#    rugc_programacion_catarsis.example:
#        class: %rugc_programacion_catarsis.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
