<?php

namespace RUGC\ProgramacionCatarsisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContenidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenidoRepository extends EntityRepository {

    public function listarOpcionesMenu() {
        $qb = $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('om')
                ->from('RUGCProgramacionCatarsisBundle:OpcionesMenu', 'om')
                ->innerJoin(
                        'RUGCProgramacionCatarsisBundle:Contenido', 'c', \Doctrine\ORM\Query\Expr\Join::WITH, 'c.opcionMenu = om.id'
                )
                ->orderBy('om.prioridad', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
