<?php

namespace RUGC\ProgramacionCatarsisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnlaceRepository extends EntityRepository
{
}
